### ISSUE TITLE
Replays not showing up

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/replay-server#2]
Replays on maps with higher versions dont show up in the vault if there is a lower version of the map uploaded.
This does affect both searching for the map name and the default list when opening the replay tab.

**Comment by JaggedAppliance** [comment]
I'm not sure this is the correct repo to post this.

**Comment by CookieNoob** [comment]
me neither, I just thought that the probability that it is read by someone who can actually fix it is much higher when I post it on github than in techsupport... feel free to move it somewhere else ;)

**Comment by JaggedAppliance** [comment]
I can't unfortunately :/

**Comment by Sheeo** [comment]
It's not the right repo -- currently the broken functionality is in the legacy-secondaryserver repo.

We need this functionality in the API instead, however. Still waiting on the [`/games`](https://github.com/FAForever/api/pull/77) route.
